import { useCallback } from 'react';
import type { StageResponse } from '../types';
import { BeforeAfterSlider } from './BeforeAfterSlider';
import { PromptDetails } from './PromptDetails';
import { DownloadIcon, SparklesIcon } from './icons';

interface ResultPanelProps {
  result: StageResponse;
}

/** Infer a file extension from a data URL's MIME type (defaults to png). */
function extensionFromDataUrl(dataUrl: string): string {
  const match = /^data:image\/([a-zA-Z0-9.+-]+);/.exec(dataUrl);
  const subtype = match?.[1]?.toLowerCase();
  if (subtype === 'jpeg') {
    return 'jpg';
  }
  return subtype ?? 'png';
}

/** Displays the staged result with a before/after slider, download, and prompt. */
export function ResultPanel({ result }: ResultPanelProps) {
  const handleDownload = useCallback(() => {
    const link = document.createElement('a');
    link.href = result.resultImage;
    link.download = `staged-${result.id}.${extensionFromDataUrl(result.resultImage)}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [result.id, result.resultImage]);

  return (
    <section aria-label="Staging result" className="animate-fade-in-up space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-sage-100 text-sage-600">
            <SparklesIcon width={18} height={18} />
          </span>
          <h2 className="font-display text-xl font-600 text-ink">Your staged room</h2>
          {result.mock && (
            <span
              title="Generated by the backend's mock provider — for demo purposes."
              className="ml-1 rounded-full border border-terracotta-200 bg-terracotta-50 px-2.5 py-0.5 text-xs font-600 text-terracotta-700"
            >
              Mock result
            </span>
          )}
        </div>
        <button
          type="button"
          onClick={handleDownload}
          className="focus-ring inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-2 text-sm font-600 text-canvas transition hover:bg-ink-soft"
        >
          <DownloadIcon width={18} height={18} />
          Download
        </button>
      </div>

      <p className="text-sm text-ink-muted">
        Drag the handle to compare the original photo with the staged version.
      </p>

      <BeforeAfterSlider beforeSrc={result.originalImage} afterSrc={result.resultImage} />

      <PromptDetails prompt={result.promptUsed} />
    </section>
  );
}
